name: Terraform Test Workflow

on:
  push:
    branches:
      - feature/mychange

jobs:
  terraform-install:
    runs-on: [self-hosted, Windows]   # runner labels ka match
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Verify Terraform Version
        run: terraform -version
