name: Terraform Test Workflow

on:
  push:
    branches:
      - feature/mychange   # sirf tumhari branch par chalega

jobs:
  terraform-install:
    runs-on: selfhostedGitHubAgent   # tumhara runner label

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Verify Terraform Version
        run: terraform -version

           
          
        
